name: Windows Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Kopeeer app
        run: dotnet restore src\Kopeeer.App\Kopeeer.App.csproj

      - name: Build Kopeeer app
        run: dotnet build src\Kopeeer.App\Kopeeer.App.csproj --configuration Release --no-restore
